version: '3'

services:
  zookeeper:
    container_name: cohesion-zookeeper
    hostname: zookeeper
    image: antlypls/zookeeper

  kafka:
    container_name: cohesion-kafka
    image: antlypls/kafka:0.10.2.1_2.11
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "events-devices:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  db-data: